### PR TITLE
fix: Fix github.com/go-delve/delve import error and add go mod

### PR DESCRIPTION
**Pull request by gadelkareem**
fixes https://github.com/beego/bee/issues/646 https://github.com/beego/bee/issues/651 https://github.com/beego/bee/issues/629 https://github.com/beego/bee/issues/601 https://github.com/beego/bee/issues/591 https://github.com/beego/bee/issues/568 https://github.com/beego/bee/issues/634 https://github.com/beego/bee/pull/649 https://github.com/beego/bee/issues/640
Error:
```
go: github.com/beego/bee imports
	github.com/beego/bee/cmd imports
	github.com/beego/bee/cmd/commands/dlv imports
	github.com/derekparker/delve/service: github.com/derekparker/delve@v1.4.0: parsing go.mod:
	module declares its path as: github.com/go-delve/delve
```

This PR does the following:
- Remove old vendor dir.
- Migrate to Go Modules.
-  Use github.com/go-delve/delve instead of the fork github.com/derekparker/delve
- Upgrade github.com/go-delve/delve to v1.3.2

To test my version use:
```
go get github.com/gadelkareem/bee@fix-mod
```

@askuy closed https://github.com/beego/bee/pull/653

### CODE REVIEW

**Comment by askuy** [comment]
> fixes #646 #651 #629 #601 #591 #568 #634 #649 #640
> Error:
> 
> ```
> go: github.com/beego/bee imports
> 	github.com/beego/bee/cmd imports
> 	github.com/beego/bee/cmd/commands/dlv imports
> 	github.com/derekparker/delve/service: github.com/derekparker/delve@v1.4.0: parsing go.mod:
> 	module declares its path as: github.com/go-delve/delve
> ```
> 
> This PR does the following:
> 
> * Remove old vendor dir.
> * Migrate to Go Modules.
> * Use github.com/go-delve/delve instead of the fork github.com/derekparker/delve
> * Upgrade github.com/go-delve/delve to v1.3.2
> 
> To test my version use:
> 
> ```
> go get github.com/gadelkareem/bee@fix-mod
> ```
> 
> @askuy closed #653
go-delve auto update, bee install is error, please fix it.

**Comment by gadelkareem** [comment]
@askuy it works fine for me. Can you provide the commands and full error please?

**Comment by askuy** [comment]
> @askuy it works fine for me. Can you provide the commands and full error please?

like this.
image

**Comment by gadelkareem** [comment]
@askuy That worked for me. 
```
> go get github.com/beego/bee@develop
go: downloading github.com/beego/bee v1.10.1-0.20200619152523-280d71a79921
go: github.com/beego/bee develop => v1.10.1-0.20200619152523-280d71a79921
```
I think you have some remaining cache. You could either clear the cache or use the latest commit for ex: 
```
go get github.com/beego/bee@280d71a
```

**Comment by askuy** [comment]
I use go get is ok，go-delve version will not change
but I use go get -u is wrong，go-delve version will auto update
image

**Comment by askuy** [comment]
> @askuy That worked for me.
> 
> ```
> > go get github.com/beego/bee@develop
> go: downloading github.com/beego/bee v1.10.1-0.20200619152523-280d71a79921
> go: github.com/beego/bee develop => v1.10.1-0.20200619152523-280d71a79921
> ```
> 
> I think you have some remaining cache. You could either clear the cache or use the latest commit for ex:
> 
> ```
> go get github.com/beego/bee@280d71a
> ```

I use go get is ok，go-delve version will not change
but I use go get -u is wrong，go-delve version will auto update

image

**Comment by gadelkareem** [comment]
Yes now I see it. Let me fix that..

**Comment by gadelkareem** [comment]
Ok made a PR for https://github.com/go-delve/delve/pull/2088 hopefully gets an eye soon

**Comment by satvirgrewal** [comment]
I am getting error after the new release when I do 'go get github.com/beego/bee'.
Error message:

`go get github.com/beego/bee
# github.com/beego/bee/cmd/commands/dlv
github.com/beego/bee/cmd/commands/dlv/dlv_amd64.go:151:3: unknown field 'AttachPid' in struct literal of type service.Config
github.com/beego/bee/cmd/commands/dlv/dlv_amd64.go:153:3: unknown field 'WorkingDir' in struct literal of type service.Config
github.com/beego/bee/cmd/commands/dlv/dlv_amd64.go:166:32: not enough arguments in call to client.Restart
        have ()
        want (bool)`

[https://github.com/beego/bee/issues/668](url)

**Comment by gadelkareem** [comment]
@satvirgrewal that's related to https://github.com/beego/bee/pull/666

**Pull request merged**
