### PR TITLE
search package from import paths, while missing type object

### PR DESCRIPTION
**Pull request by LnZd**
## What this PR does:

Support struct field type outside of project directory. When bee generate docs, packages are only loaded from current project directory.Therefore bee cannot find struct filed type from package ouside of the project directory.

## Solution:

Check the import path of struct field type, loded package while the pacakge are not loaded.

## fix issue 
#605

### CODE REVIEW

**Comment by allupaku** [comment]
any update on this ?

**Review by flycash — CHANGES_REQUESTED** [review]
Please resolve conflicts and add unit tests.

**Review by flycash — CHANGES_REQUESTED** [review]
Could you please add unit tests for this PR and provide more detail about the issue solved by this issue?

**Comment by flycash** [comment]
Please add unit tests and I will test it this weekend.

**Review by flycash — CHANGES_REQUESTED** [review]
Please add unit tests. We wants to improve the code coverages, so new PR without unit tests is not acceptable.

**Comment by flycash** [comment]
Thank you, let me test it tomorrow.

**Review by flycash — APPROVED** [review]

**Pull request merged**
