### PR TITLE
Refactor

### PR DESCRIPTION
**Pull request by sergeylanzman**
Refactor! no change logic  or flow!
- [X] create sub packages
- [X] delete unused code
- [X] delete code from not use command cmdRouter,cmdTest, cmdRundocs
- [X] make command more plugins
- [X] check with gosimple, staticcheck, go vet, unused, unconvert

### CODE REVIEW

**Comment by sergeylanzman** [comment]
@astaxie Done! I use this version and no have problems.

**Comment by astaxie** [comment]
@sergeylanzman seems have conflicts

**Comment by sergeylanzman** [comment]
@astaxie fixed

**Comment by sergeylanzman** [comment]
@amrfaissal But now if command have a lot of code we can split to many files and not one big file with 1K loc. Other options you can import command from other repo with one import line

**Comment by amrfaissal** [comment]
@sergeylanzman Ok it makes sense in this case. Also It can help to refactor the commands and make them more testable. As we all know, `bee` does not have any unit tests which is what we need to focus on in the future :-)

**Comment by astaxie** [comment]
LGTM

**Pull request merged**
