### PR TITLE
Enable doc generation outside of gopath

### PR DESCRIPTION
**Pull request by franzwilhelm**
To support #549

### CODE REVIEW

**Comment by franzwilhelm** [comment]
@amrfaissal Please review and merge :+1:

**Comment by franzwilhelm** [comment]
I realize further fixes must be done here as well to make router comments generate: https://github.com/astaxie/beego/blob/8134a89e81c168d7125808b6135240016c10bc40/router.go#L261

**Comment by amrfaissal** [comment]
@franzwilhelm Any updates on this one? Thanks

**Comment by franzwilhelm** [comment]
@amrfaissal No sorry I haven't had time to focus on it. Thing is, the whole beego framework has a lot of places where GOPATH is used and targeted explicitly in the code, so it's harder refactoring, as we need to check working directory and so on, as well as checking the GOPATH whenever dealing with it. And the repos aren't really that well modularized, so there are a lot of places to apply changes. But I'll have a look when I get the chance

**Pull request closed without merging**
