### PR TITLE
merge default config with config file

### PR DESCRIPTION
**Pull request by sergeylanzman**

### CODE REVIEW

**Comment by amrfaissal** [comment]
This PR breaks `bee`. Every time it's called it loads the configuration  and logs it before anything else!
Before, `loadConfig()` walks the current folder looking for `bee.json` or `Beefile` and it **fallsback** to the default configuration.

image

**Comment by sergeylanzman** [comment]
Why breaks? First load default and after this rewrite setting from Beefile. Currently if you set one setting in Beefile this not load default.

**Comment by amrfaissal** [comment]
This is another screenshot. The banner is intended to appear in the begining:
image

**Comment by sergeylanzman** [comment]
Second screenshot this without Beefile. Why this problem load config before all?

**Comment by amrfaissal** [comment]
Because `loadConfig` is called inside the `init()` function of the `config` package and each time the package is imported it gets called.

**Comment by sergeylanzman** [comment]
https://golang.org/ref/spec#Package_initialization
```
A package with no imports is initialized by assigning initial values to all its package-level variables
followed by calling all init functions in the order they appear in the source, possibly in multiple files, as presented to the compiler. If a package has imports, the imported packages are initialized before initializing the package itself. If multiple packages import a package, the imported package will be 
initialized only once. The importing of packages, by construction, guarantees that there can be no 
cyclic initialization dependencies.
```

**Comment by amrfaissal** [comment]
There are two problem here:

(1) The banner should appear first, then the configuration loading. In the screenshots, the configuration loading always happens first.

(2) The default configuration is loaded first, then if there is a `Beefile` or `bee.json` in the current directory, it will be overrided. The problem is `loadConfig()` walks the current directory recursively. So if your current directory does not have a `Beefile` or `bee.json`, it might load the configuration from another Beego application which has it and simply because of `filepath.Walk()`.

So this change, loads the configuration no matter what. There are other commands that does not need this configuration, like `bee new`.

**Comment by sergeylanzman** [comment]
1. Banner first => need move ShowShortVersionBanner to main.go, we show banner from on all commands. Better write once in main func.
2. Before this pr, loadConfig use filepath.Walk() and load Beefile from other project in current directory. `bee` must be run in project directory and not support beego project in beego project
from Documentation:
```
quickstart
├── conf
│   └── app.conf
├── controllers
│   └── default.go
├── main.go
├── models
├── routers
│   └── router.go
├── static
│   ├── css
│   ├── img
│   └── js
├── tests
│   └── default_test.go
└── views
    └── index.tpl
```

```
➜  src  cd quickstart
➜  quickstart  bee run
```
You're right about `bee new` not need configuration(currenly), but if you create new project filepath.Walk() don't find Beefile  and load default settings.
I think we need replace filepath.Walk() and set Beefile in root project like Dockerfile, Gemfile and other XXXfile and not support Beefile in other subfolder. Maybe root and conf folder

**Comment by astaxie** [comment]
@sergeylanzman could you send a fix for this?

**Comment by sergeylanzman** [comment]
@astaxie fix for banner first?

**Comment by amrfaissal** [comment]
I'm working on a fix.

**Pull request merged**
