### PR TITLE
fix bee hprose error.

### PR DESCRIPTION
**Pull request by Lao-liu**
fix bee hprose error.

### CODE REVIEW

**Comment by amrfaissal** [comment]
@astaxie This change breaks the `hprose` command as it make use of `ColorLog` which is no longer supported.
@Lao-liu Please make sure you have the latest version of `develop` branch.

I have merged a fix to this, including the check if `appname` argument is missing.

**Comment by astaxie** [comment]
we need to add trivas into the bee repo.

**Comment by amrfaissal** [comment]
I don't have sufficient rights to enable the repository on Travis.

**Comment by astaxie** [comment]
@amrfaissal I just add the travis now.

**Pull request merged**
