### PR TITLE
support enum, except iota and type inference.

### PR DESCRIPTION
**Pull request by ilylia**
support enum, except iota and type inference. and move swagger.go from astaxie/beego to here, add Enum field to Schema.

### CODE REVIEW

**Comment by astaxie** [comment]
Could you create two PR?

`swagger.go` should update to beego repo

**Comment by ilylia** [comment]
but why you put `swagger.go` in beego repo? i didnt found any reference of `Swagger` in it.

**Comment by ilylia** [comment]
[update `swagger.go` in beego repo](https://github.com/astaxie/beego/pull/2928)

**Comment by ilylia** [comment]
this ci check will be failed until you merge the pr #2928 in beego repo and update vendor in this repo.

**Pull request merged**
