### PR TITLE
[g_docs] Refactor definition generation

### PR DESCRIPTION
**Pull request by wy-z**
- replace 'getModel' with [wy-z/tspec](https://github.com/wy-z/tspec)
- better pointer support
- better anonymous struct support
- faster and more clear 

Signed-off-by: weiyang <weiyang.ones@gmail.com>

### CODE REVIEW

**Comment by wy-z** [comment]
@astaxie review pls

**Comment by sergeylanzman** [comment]
@wy-z 
Hi 
Thank about your amazing PR. I will check it's on few projects in few days. 
But 2 issues:
1. Send pr to developer branch.
2. Your package wy-z/tspec use License GPLV3 and bee use apache 2. I think if we use your package we need change bee License. @astaxie WDYT?

**Comment by wy-z** [comment]
@sergeylanzman take it easy~how about `MIT`?
https://github.com/wy-z/tspec/commit/8b7079995ab940dde029bbf72ba7ec65ffe328de

**Comment by sergeylanzman** [comment]
@wy-z 
I think MIT it's ok.
OK check diff in swagger output in few service in my company.

Again Thank you :)!

**Comment by sergeylanzman** [comment]
1. You have conflict with develop branch
2. github.com/go-openapi/spec very cool, but don't support yaml. I get yaml with all properties 3000+lines

I don't know if we need this.
@astaxie  Your choice

**Comment by wy-z** [comment]
@sergeylanzman I'm sorry, this is my mistake...
https://github.com/beego/bee/pull/467/commits/3e220b19595d367cd98a157be3a514db7be81d6a

**Comment by wy-z** [comment]
@sergeylanzman there is some trouble...
[wy-z/tspec](https://github.com/wy-z/tspec) need `Schema.AllOf` for struct inheriting, but `beego/swagger.Schema` does not...

**Comment by wy-z** [comment]
-1

**Comment by wy-z** [comment]
+1

**Comment by wy-z** [comment]
@sergeylanzman [wy-z/tspec](https://github.com/wy-z/tspec) has released with `1.0.0`~
review, pls

**Comment by astaxie** [comment]
I don't want to import so many third party package. I don't think it simplify the logic. It just transfer to other package which is not controlled by bee

**Comment by wy-z** [comment]
@astaxie  you can fork it ... or close the pull request, thanks

**Pull request closed without merging**
