### PR TITLE
Swagger: support default value columns for @Param

### PR DESCRIPTION
**Pull request by xiaoqiang0**
This patch support default value after 'type' column if total
columns is six.

This enhancement also is compatiable with old five columns.

### CODE REVIEW

**Comment by xiaoqiang0** [comment]
This PR depend on:

https://github.com/astaxie/beego/pull/2251

**Comment by astaxie** [comment]
I think it's already support default in swagger now

**Comment by xiaoqiang0** [comment]
Thanks for your reply.

AFAIK, @Param only support five columns currently, so how to set the default value.

I also have checked the source code of bee/g_docs.go there no any code set *.Default.

Could you please give an example?

**Comment by astaxie** [comment]
I mean this one https://github.com/beego/bee/pull/292

**Comment by xiaoqiang0** [comment]
多谢，我看了一下，这个似乎只是针对object,结构体，无法针对单个query 参数使用吧，可能我理解有误，能给个例子吗，就一个参数如何设置默认值。

**Pull request closed without merging**
