### PR TITLE
add Beefile yml

### PR DESCRIPTION
**Pull request by sergeylanzman**
Add Beefile(yml file) like( guardfile,dockerfile etc...)
@astaxie  Maybe  drop bee.json support ?

### CODE REVIEW

**Comment by astaxie** [comment]
Cool idea

**Comment by sergeylanzman** [comment]
@astaxie  drop json support?

**Comment by astaxie** [comment]
@sergeylanzman I think so

**Comment by sergeylanzman** [comment]
and I want to refactor to all "generation block". it is ok now?

**Comment by astaxie** [comment]
what's your main idea?

**Comment by sergeylanzman** [comment]
Clear code and to do easy add support any db driver and any generation. Now we need set many  if's for postgres is igly

**Comment by astaxie** [comment]
@sergeylanzman go for it . That be highly appreciated

**Pull request merged**
