### PR TITLE
Add support for apps outside of gopath with go modules, fixes #549

### LINKED ISSUE #549: Add support with go modules
Currently, running bee for an application outside of `$GOPATH` produces this error:

```
______
| ___ \
| |_/ /  ___   ___
| ___ \ / _ \ / _ \
| |_/ /|  __/|  __/
\____/  \___| \___| v1.10.0
2018/10/06 11:33:16 FATAL    ▶ 0001 No application '[current working directory]' found in your GOPATH
```

### PR DESCRIPTION
**Pull request by franzwilhelm**
@astaxie @amrfaissal @sergeylanzman  Please review and merge. Using my fork in production application until this is included into a release

### CODE REVIEW

**Comment by franzwilhelm** [comment]
This makes bee able to run applications based on go modules: https://github.com/golang/go/wiki/Modules, which supports being run outside of the `$GOPATH`

**Comment by amrfaissal** [comment]
Thanks for the PR!

**Comment by franzwilhelm** [comment]
@amrfaissal Do you know when we can expect the next release?

**Comment by amrfaissal** [comment]
@franzwilhelm I don't have that information. I think you should reach to @astaxie on the Slack channel regarding releases and the roadmap. If you're not on the Slack channel, just leave me an email address of yours and I will invite you.

**Comment by franzwilhelm** [comment]
@amrfaissal Already did a couple of days ago :+1:

**Pull request merged**
