### PR TITLE
Fix github.com/go-delve/delve import error 

### PR DESCRIPTION
**Pull request by gadelkareem**
fixes https://github.com/beego/bee/issues/646 https://github.com/beego/bee/issues/651 https://github.com/beego/bee/issues/629 https://github.com/beego/bee/issues/601 https://github.com/beego/bee/issues/591 https://github.com/beego/bee/issues/568 https://github.com/beego/bee/issues/634 https://github.com/beego/bee/pull/649 https://github.com/beego/bee/issues/640
Error:
```
go: github.com/beego/bee imports
	github.com/beego/bee/cmd imports
	github.com/beego/bee/cmd/commands/dlv imports
	github.com/derekparker/delve/service: github.com/derekparker/delve@v1.4.0: parsing go.mod:
	module declares its path as: github.com/go-delve/delve
```

This PR does the following:
- Remove old vendor dir.
- Migrate to Go Modules.
-  Use github.com/go-delve/delve instead of the fork github.com/derekparker/delve
- Upgrade github.com/go-delve/delve to v1.3.2

To test my version use:
```
go get github.com/gadelkareem/bee@fix-mod
```

### CODE REVIEW

**Comment by RudyPeng** [comment]
finally works,thx

**Comment by guhan121** [comment]
@gadelkareem 你的头像看着好眼晕

**Comment by guhan121** [comment]
@astaxie  大神出来合PR啦

**Comment by guhan121** [comment]
@gadelkareem

**Comment by gadelkareem** [comment]
@guhan121 use `go get github.com/gadelkareem/bee@fix-mod` to test this PR

**Comment by askuy** [comment]
> fixes #646 #651 #629 #601 #591 #568 #634 #649 #640
> Error:
> 
> ```
> go: github.com/beego/bee imports
> 	github.com/beego/bee/cmd imports
> 	github.com/beego/bee/cmd/commands/dlv imports
> 	github.com/derekparker/delve/service: github.com/derekparker/delve@v1.4.0: parsing go.mod:
> 	module declares its path as: github.com/go-delve/delve
> ```
> 
> This PR does the following:
> 
> * Remove old vendor dir.
> * Migrate to Go Modules.
> * Use github.com/go-delve/delve instead of the fork github.com/derekparker/delve
> * Upgrade github.com/go-delve/delve to v1.3.2
> 
> To test my version use:
> 
> ```
> go get github.com/gadelkareem/bee@fix-mod
> ```

please rebase your commit
refer #https://github.com/sunyongjian/blog/issues/29

**Comment by gadelkareem** [comment]
Moved to https://github.com/beego/bee/pull/665

**Pull request closed without merging**
