### PR TITLE
Fixes configuration loading since last changes

### PR DESCRIPTION
**Pull request by amrfaissal**
This fixes the changes made in #369.

### CODE REVIEW

**Comment by sergeylanzman** [comment]
after this PR if you set beefile with one setting this not load other setting from default.

**Comment by amrfaissal** [comment]
@sergeylanzman The last commit fixes that behavior and makes sure default values are loaded.

**Comment by astaxie** [comment]
`config.LoadConfig()` can we move to one place for all the commands?

**Comment by amrfaissal** [comment]
@astaxie Yes. I think the best place would be after `cmd.PreRun()` in `main.go`:
```
  if c.PreRun != nil {
     c.PreRun(c, args)
  }
  // Load configuration
  config.LoadConfig()
```

**Comment by astaxie** [comment]
> @astaxie Yes. I think the best place would be after cmd.PreRun() in main.go:
> 
>   if c.PreRun != nil {
>      c.PreRun(c, args)
>   }
>   // Load configuration
>   config.LoadConfig()

yea, maybe we can add some hooks here for the future

**Comment by sergeylanzman** [comment]
@astaxie @amrfaissal Ok Now this load config in all command, this work before with init func in my pr https://github.com/beego/bee/pull/369. We return to back(load config in all command and merge default config)

**Comment by amrfaissal** [comment]
@sergeylanzman `staticcheck` is complaining about empty `if` blocks in `g_docs`. Is there a reason why `beeLogger.Log.Fatalf()` is commented out in multiple places in `g_docs.go`?

```golang
f, err := parser.ParseFile(fset, path.Join(curpath, "routers", "router.go"), nil, parser.ParseComments)
if err != nil {
   // beeLogger.Log.Fatalf("Error while parsing router.go: %s", err)
}
```

**Comment by sergeylanzman** [comment]
@amrfaissal Not reasons I will fix this.

**Comment by amrfaissal** [comment]
No worries, I will push a fix in this PR. Thanks.

**Comment by amrfaissal** [comment]
@astaxie @sergeylanzman The build failed for Go 1.8 because of `gosimple`:
```
cmd/commands/run/watch.go:87:18: should use time.Until instead of t.Sub(time.Now()) (S1024)
```
Since `time.Until` was recently introduced in Go 1.8, we cannot replace `t.Sub` with it as `bee` will break for older Go versions. I've already changed `.travis.yml` to ignore this check by `gosimple` but it seems TravisCI didn't pick it up. Do you have any idea why?

**Comment by sergeylanzman** [comment]
very strange because gosimple check until if this not go1.8
https://github.com/dominikh/go-tools/blob/89a8bf9d32d7bf42e8a6e83c21177a2a029a2f0c/simple/lint.go#L784

**Comment by astaxie** [comment]
@amrfaissal travis cache the config. So you need to create another PR and close this one.

**Comment by amrfaissal** [comment]
@astaxie build fixed.

**Pull request merged**
