### PR TITLE
Release 1.8.1

### PR DESCRIPTION
**Pull request by amrfaissal**
This is a staging branch for **1.8.1 Release** :tada:
Merge conflicts are fixed and the version bumped to 1.8.1.

### CODE REVIEW

**Comment by astaxie** [comment]
@amrfaissal maybe just send the PR from develop branch to master.

**Comment by astaxie** [comment]
But I am okay for this PR. 🎈👏

**Comment by amrfaissal** [comment]
@astaxie  I had to fix some merge conflicts and I did it in a separate branch.

**Comment by astaxie** [comment]
@amrfaissal okay, make sense. So we bump it now. Thanks for you guys.

**Comment by amrfaissal** [comment]
@astaxie Don't forget to create a tag for this release :smiley:.

**Comment by astaxie** [comment]
yea, I am try to use this command to build all system binary. but it looks has error now.

`goxc -bc="linux,windows,darwin" -pv=1.8.0`

**Comment by astaxie** [comment]
It looks the delve package has some issues to build the specific system.
```
# github.com/beego/bee/vendor/github.com/derekparker/delve/pkg/proc
vendor/github.com/derekparker/delve/pkg/proc/proc.go:54: undefined: OSProcessDetails
vendor/github.com/derekparker/delve/pkg/proc/threads.go:24: undefined: WaitStatus
# github.com/beego/bee/vendor/github.com/derekparker/delve/pkg/proc
vendor/github.com/derekparker/delve/pkg/proc/disasm.go:9: undefined: ArchInst
# github.com/beego/bee/vendor/github.com/derekparker/delve/pkg/proc
vendor/github.com/derekparker/delve/pkg/proc/disasm.go:9: undefined: ArchInst
# github.com/beego/bee/vendor/github.com/derekparker/delve/pkg/proc
vendor/github.com/derekparker/delve/pkg/proc/disasm.go:9: undefined: ArchInst
[goxc:xc] 2017/03/23 22:27:09 'go' returned error: Wait error: exit status 2: # github.com/beego/bee/vendor/github.com/derekparker/delve/pkg/proc
vendor/github.com/derekparker/delve/pkg/proc/proc.go:54: undefined: OSProcessDetails
vendor/github.com/derekparker/delve/pkg/proc/threads.go:24: undefined: WaitStatus
[goxc:xc] 2017/03/23 22:27:09 Error: Wait error: exit status 2: # github.com/beego/bee/vendor/github.com/derekparker/delve/pkg/proc
vendor/github.com/derekparker/delve/pkg/proc/proc.go:54: undefined: OSProcessDetails
vendor/github.com/derekparker/delve/pkg/proc/threads.go:24: undefined: WaitStatus
[goxc:xc] 2017/03/23 22:27:09 Have you run `goxc -t` for this platform (386,darwin)???
[goxc:xc] 2017/03/23 22:27:10 'go' returned error: Wait error: exit status 2: # github.com/beego/bee/vendor/github.com/derekparker/delve/pkg/proc
vendor/github.com/derekparker/delve/pkg/proc/disasm.go:9: undefined: ArchInst
[goxc:xc] 2017/03/23 22:27:10 Error: Wait error: exit status 2: # github.com/beego/bee/vendor/github.com/derekparker/delve/pkg/proc
vendor/github.com/derekparker/delve/pkg/proc/disasm.go:9: undefined: ArchInst
[goxc:xc] 2017/03/23 22:27:10 Have you run `goxc -t` for this platform (386,windows)???
[goxc:xc] 2017/03/23 22:27:10 'go' returned error: Wait error: exit status 2: # github.com/beego/bee/vendor/github.com/derekparker/delve/pkg/proc
vendor/github.com/derekparker/delve/pkg/proc/disasm.go:9: undefined: ArchInst
[goxc:xc] 2017/03/23 22:27:10 Error: Wait error: exit status 2: # github.com/beego/bee/vendor/github.com/derekparker/delve/pkg/proc
vendor/github.com/derekparker/delve/pkg/proc/disasm.go:9: undefined: ArchInst
[goxc:xc] 2017/03/23 22:27:10 Have you run `goxc -t` for this platform (386,linux)???
[goxc:xc] 2017/03/23 22:27:10 'go' returned error: Wait error: exit status 2: # github.com/beego/bee/vendor/github.com/derekparker/delve/pkg/proc
vendor/github.com/derekparker/delve/pkg/proc/disasm.go:9: undefined: ArchInst
[goxc:xc] 2017/03/23 22:27:10 Error: Wait error: exit status 2: # github.com/beego/bee/vendor/github.com/derekparker/delve/pkg/proc
vendor/github.com/derekparker/delve/pkg/proc/disasm.go:9: undefined: ArchInst
[goxc:xc] 2017/03/23 22:27:10 Have you run `goxc -t` for this platform (arm,linux)???
[goxc:xc] 2017/03/23 22:27:10 Multiple errors (returning first one): [Wait error: exit status 2: # github.com/beego/bee/vendor/github.com/derekparker/delve/pkg/proc
vendor/github.com/derekparker/delve/pkg/proc/proc.go:54: undefined: OSProcessDetails
vendor/github.com/derekparker/delve/pkg/proc/threads.go:24: undefined: WaitStatus Wait error: exit status 2: # github.com/beego/bee/vendor/github.com/derekparker/delve/pkg/proc
vendor/github.com/derekparker/delve/pkg/proc/disasm.go:9: undefined: ArchInst Wait error: exit status 2: # github.com/beego/bee/vendor/github.com/derekparker/delve/pkg/proc
vendor/github.com/derekparker/delve/pkg/proc/disasm.go:9: undefined: ArchInst Wait error: exit status 2: # github.com/beego/bee/vendor/github.com/derekparker/delve/pkg/proc
vendor/github.com/derekparker/delve/pkg/proc/disasm.go:9: undefined: ArchInst]
[goxc:xc] 2017/03/23 22:27:10 Stopping after 'xc' failed with error 'Wait error: exit status 2: # github.com/beego/bee/vendor/github.com/derekparker/delve/pkg/proc
vendor/github.com/derekparker/delve/pkg/proc/proc.go:54: undefined: OSProcessDetails
vendor/github.com/derekparker/delve/pkg/proc/threads.go:24: undefined: WaitStatus'
[goxc] 2017/03/23 22:27:10 RunTasks error: Wait error: exit status 2: # github.com/beego/bee/vendor/github.com/derekparker/delve/pkg/proc
vendor/github.com/derekparker/delve/pkg/proc/proc.go:54: undefined: OSProcessDetails
vendor/github.com/derekparker/delve/pkg/proc/threads.go:24: undefined: WaitStatus
```

**Comment by amrfaissal** [comment]
Ok I am looking at it.

**Comment by astaxie** [comment]
https://github.com/derekparker/delve/issues/198#issuecomment-173957938

**Pull request merged**
